version: '3'

services:
  shrine-db:
    container_name: shrine_mysql  
    hostname: shrine_mysql
    build:
      context: .
      dockerfile: deployment/shrine_mysql
    image: shrine_mysql:test
    networks:
      - shrine_network
    healthcheck:
        test: ["CMD", "mysql", "--version"]
        interval: 5s
        timeout: 10s
        retries: 5
   

  shrine-fastapi:
    container_name: shrine_fastapi
    hostname: shrine_fastapi
    build:
      context: .
      dockerfile: deployment/shrine_fastapi
    image: shrine_fastapi:test
    networks:
      - shrine_network
    ports:
      - "8000:80"
    depends_on:
      - shrine-db
    

  shrine-react:
    container_name: shrine_react
    build:
      context: .
      dockerfile: deployment/shrine_react
    image: shrine_react:test
    ports:
      - "3000:3000"
#    command: bash -c 'while [[ "$$(curl --connect-timeout 2 -s -o /dev/null -w ''%{http_code}'' uds-mock-server:4000/readiness)" != "200" ]]; do echo ..; sleep 5; done; echo backend is up;npm start'
    depends_on:
      - shrine-fastapi

  shrine-test:
    container_name: shrine_test
    build:
      context: .
      dockerfile: deployment/shrine_pytest
    image: shrine_test:test
    networks:
      - shrine_network
    depends_on:
      - shrine-fastapi

networks:
  shrine_network: {}
